server:
  port: 10000

spring:
  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 2048MB


#ip地址格式
ipFormat: 192.168.0

#本机电脑文件保存目录
fileAddr: D:\tmp\file\
#文件下载请求路径前缀
filePath: development/file/**


